version: '3.4'
services:
  maven-sdk-paperarch-share:
    image: alfresco-share-maven-sdk-paperarch:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../maven-sdk-paperarch-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: maven-sdk-paperarch-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  maven-sdk-paperarch-acs:
    image: alfresco-content-services-maven-sdk-paperarch:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../maven-sdk-paperarch-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - maven-sdk-paperarch-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - maven-sdk-paperarch-postgres
  maven-sdk-paperarch-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - maven-sdk-paperarch-db-volume:/var/lib/postgresql/data
  maven-sdk-paperarch-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: maven-sdk-paperarch-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: maven-sdk-paperarch-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - maven-sdk-paperarch-ass-volume:/opt/alfresco-search-services/contentstore
      - maven-sdk-paperarch-ass-volume:/opt/alfresco-search-services/data
volumes:
  maven-sdk-paperarch-acs-volume:
    external: true
  maven-sdk-paperarch-db-volume:
    external: true
  maven-sdk-paperarch-ass-volume:
    external: true